version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            ls -la
            npm install
            npm run eslint
            npm run format:check
            npm run build
            npx semantic-release --dry-run
            npx semantic-release --dry-run > sem-rel-dry-run.txt
            echo
            echo "catted file:"
            cat sem-rel-dry-run.txt

            if test "abc" = "abc"
            then
            echo "equals"
            else
            echo "not equals"
            fi

            if grep "The next release version is" sem-rel-dry-run.txt
            then
              dry_run_version=$(cat sem-rel-dry-run.txt | grep "The next release version is" | sed -n -e 's/^.*is //p')
              echo "Dry run version: ${dry_run_version}"
            elif grep "a new version won't be published" sem-rel-dry-run.txt
            then
              echo "a new version won't be published"
            else
              echo "unknown semantic-release dry-run state - failing"
            exit 1
            fi


  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Create binaries with pkg
          command: |
            npm run pkg
            ls -la
            # npm install
            # npm run build
            shasum -a 256 ts-sem-rel-circle-linux > ts-sem-rel-circle-linux.sha256
            shasum -a 256 ts-sem-rel-circle-macos > ts-sem-rel-circle-macos.sha256
            shasum -a 256 ts-sem-rel-circle-win.exe > ts-sem-rel-circle-win.exe.sha256
            ls -la
      - run:
          name: Semantic Release
          command: |
            npx semantic-release --dry-run
            # npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
